name: dashenv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libexpat=2.7.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libzlib=1.3.1
  - openssl=3.0.18
  - packaging=25.0
  - pip=25.3
  - python=3.13.11
  - python_abi=3.13
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.4.0
      - dash-bootstrap-components==2.0.4
      - flask==3.1.2
      - fonttools==4.61.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - nest-asyncio==1.6.0
      - numpy==2.4.1
      - pandas==3.0.0
      - pillow==12.1.0
      - plotly==6.5.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.30.0
      - six==1.17.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - zipp==3.23.0
prefix: C:\Users\Joe\anaconda3\envs\dashenv
